### ISSUE TITLE
[Feedback] Release Report Budget

### ISSUE THREAD

**Issue by youngcw** [actualbudget/actual#2999]
The Report Budget option needs just a few things before it can be released fully.

- [x] A more permanent way to select budget type instead of the current budget page selector.  Probably a setting in the settings page (#3017)
- [x] Update the docs page and move it out of experimental actualbudget/docs#483
- [ ] Optional: A way to select this budget type when making a fresh budget.  Could be coupled with an option to set the budget name.  Related #1889 
- [ ] Optional: Remove the rollover option since it makes the math really confusing in the report budget table. (this or the following but not both)
- [ ] Optional: Change how the rollover math works to make the table totals not super confusing. (this or the previous, but not both)
- [ ] Optional: Make hidden categories not count towards budget totals in Tracking Budget.  Since this budget type essentially resets every month, it could be useful for people to be able have categories not apply towards the budget, but have a category to remove the red banner.
- [x] Optional: rename the budget types.  Report and Rollover are not especially descriptive. (Has been changed in the GUI to Envelope and Tracking. May need changed other places)
- [ ] Optional: Add function to migrate between the two

**Comment by Teprifer** [comment]
To the last optional point on naming, not too fussed, but Traditional doesn't quite seen right, since while kinda true, it's also less descriptive and is suggestive it should be preferred. Could be 'Tracking' and 'Envelope'?

I also think the envelope should have (Default) or (Recommended) beside it when selecting type in keeping with Actual's history and being the primary budget type. It's also what actual is most known for (a YNAB alternate).

**Comment by jsehnoutka** [comment]
Not sure if Budget types are meant to be interlinked, I've always used them as complementary to each other.  But if yes, I would suggest looking into #732. Maybe a dropdown menu of the Report budget could be extended with "Synchronize budgets" button?

**Comment by MatissJanis** [comment]
> A way to select this budget type when making a fresh budget. Could be coupled with an option to set the budget name. 

TBH I think we shouldn't do this. We should be removing steps from the onboarding flow, not adding more.

**Comment by psybers** [comment]
I'm not sure dropping the rollover capability is a good idea.  I am not sure how other people are using this, but that is still needed for me for a few categories (that typically have yearly or bi-yearly charges).  Otherwise you really can't budget for those without some sort of rollover.

**Comment by psybers** [comment]
FYI I started work on having hidden categories not affect this budget.  I have two bugs I am tracking down and then I will probably PR that.

**Comment by youngcw** [comment]
> > A way to select this budget type when making a fresh budget. Could be coupled with an option to set the budget name.
> 
> TBH I think we shouldn't do this. We should be removing steps from the onboarding flow, not adding more.

I don't think a selector is needed, but I think people would like the option to set a name upon budget creation. If we do that, then its not a big deal to also add a type selector imo.

**Comment by MatissJanis** [comment]
> I don't think a selector is needed, but I think people would like the option to set a name upon budget creation. If we do that, then its not a big deal to also add a type selector imo.

Is budget name critical to get started? I would argue - no, it's optional. The onboarding should have as little friction as possible in order to allow new users to try out the product without needing to fill out forms and/or make decisions that could be made at a later date. Just click "try now" -> import an existing budget -> boom, you're ready to try it out. Simple as that.

**Comment by youngcw** [comment]
> I'm not sure dropping the rollover capability is a good idea. I am not sure how other people are using this, but that is still needed for me for a few categories (that typically have yearly or bi-yearly charges). Otherwise you really can't budget for those without some sort of rollover.

The only reason I would like to drop the ability is that the math for the budget totals gets weird.  So if that could be made less weird, or the docs updated to make understanding those numbers easier, that would be fine with me.

**Comment by MatissJanis** [comment]
Feedback: https://github.com/actualbudget/actual/issues/3346

**Comment by psybers** [comment]
@57194 I have been using it for a year and it is quite stable. You shouldn't lose data.

I would say it is pretty close to moving out of experimental.  I personally would like to see hidden categories not affect the tracking budget, but other than that I see no problems with it in its current form.

**Comment by joel-rich** [comment]
Hey everyone, I have a suggestion/request for this item:

> Optional: Make hidden categories not count towards budget totals in Tracking Budget. Since this budget type essentially resets every month, it could be useful for people to be able have categories not apply towards the budget, but have a category to remove the red banner.

I understand if this adds too much complexity, but would it be feasible to have a separate "don't count this" tag for a category rather than not counting every hidden category? That would solve a couple issues with the way I'd like to use tracking budgeting.

- I have some categories that are hidden because they're not relevant anymore, but I still want them properly counted historically (ie: I have hidden my "Pets" category since I no longer have a pet, but it should still be included in calculations if I look back at previous year's budgets). 
- I would like to have a category show in the budget page, but not count towards calculation - I have a "Savings" category which is the amount I've transferred to an off-budget account that I want to visibly see, but it doesn't make sense to have it count against the "monthly saved" calculation. 

Thanks for your consideration.

As an aside, I've very excited to switch to this budget type - I've essentially been using Actual in this way for a couple years by using a "Projected Income" budget line with negative amounts budgeted for future months, but it has been a bit clunky at times.

**Comment by psybers** [comment]
I wonder what the purpose of 'hidden' categories is for an envelope budget?  Is that really just acting more like an 'archived' category?  Maybe that feature should be renamed to 'archived'?  And then for tracking budgets, a new feature added called 'hidden' that hides it from the budget (but it is not archived/hidden in the UI)?

**Comment by WaterBloom** [comment]
Hello! I ran into an issue I need advice with.

I switched to the Tracking budget mode, and everything works well, except for this: on the main /budget page, "Expenses" and "Spent" shows one number. But if I go to Reports > Cash Flow > specific month, the number there is lower, sometimes significantly so.

If I search all accounts and select only items with "Payments", the total matches Cash Flow report, so that number is accurate, and is what I would like displayed on the main page.

(If relevant: I do transfers between accounts that are properly marked as such, and I currently don't have any accounts "off-budget". Also, "Income" seems calculated correctly.)

What could be the culprit? How do they calculate things differently?

**Comment by AWare** [comment]
I really prefer this budget type so 🥇 

For hidden transactions, I just use this as a way to archive no longer relevant budgets. Such as if I need to budget for some specific thing, I can just hide that budget when it's over.

For rolled over budgets, this is useful for tracking spend that's going to be repaid- like work budgets or healthcare cash plans.

**Comment by joel-rich** [comment]
> I wonder what the purpose of 'hidden' categories is for an envelope budget? Is that really just acting more like an 'archived' category? Maybe that feature should be renamed to 'archived'? And then for tracking budgets, a new feature added called 'hidden' that hides it from the budget (but it is not archived/hidden in the UI)?

I think calling the new tag "Tracked" or something similar would make more sense. To me, "Hidden" implies visually hidden and I'd be confused if I clicked a "Hide" button and only a total at the top of the page changed. Could have the category dropdown show "Rename / (Hide | Show or Archive | Unarchive(?)) / (Untrack | Track) / Delete"

**Comment by joel-rich** [comment]
Has anyone had issues with this budget not filling in budgeted amounts? It seems fine if everything stays local, but doesn't seem to sync between devices properly and amounts also don't show after an export/import.

**Comment by youngcw** [comment]
> Has anyone had issues with this budget not filling in budgeted amounts? It seems fine if everything stays local, but doesn't seem to sync between devices properly and amounts also don't show after an export/import.

@joel-rich Does it still do it if you test on edge.actualbudget.org?

**Comment by joel-rich** [comment]
@youngcw That build seems fine. Old exports still have nothing filled, but it's good if I fill the budget on edge and export then import again. 

Edge is latest daily master so it'll be good next release?

**Comment by youngcw** [comment]
> @youngcw That build seems fine. Old exports still have nothing filled, but it's good if I fill the budget on edge and export then import again.
> 
> Edge is latest daily master so it'll be good next release?

Yes, everything in current edge will be in the next release.

**Comment by youngcw** [comment]
@MatissJanis I did the needed updates to the docs page.  So this is minimally ready for release.

**Comment by velotelo** [comment]
What's the proper way to plan a budget for N months ahead with tracked option? Although I can plan each month's expenses and incomes separately, I can't find a way to link the results of previous and next months together.

Say, I start with 0€ in my account on January 1st. My "projected savings" in January are 1000€, so I expect to have 1000€ in my account on January 31st.
In February I plan spending more and my "projected savings" are -1000€, so end of February I should have 0€ in my account.
How should I transfer the projected result of January to February? Currently I just copy the "projected savings" into the "starting balances" of the following month. Is that the right approach? 
But then end of each month I have to manually update those "starting balances" for future months. It would be nice if that could be handled automatically like in envelope budgeting.

P.S. The envelope option doesn't work for me, since there's no way to plan my budget for next N months if I'm not able to budget in my income as well.

**Comment by MatissJanis** [comment]
Report (tracking) budget will be released as a first party feature in v24.12.0. If there are any further feedback items and/or bug reports - please open individual issues.

Thanks to everyone that collaborated on this!
