### ISSUE TITLE
[Feedback] Dashboards (reports homepage)

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#3282]
**Dashboards** feature allows customising your reports homepage. With widgets and layout defined by you.

To enable the feature - head over to _experimental features_ and toggle the **dashboards** feature flag. Next head to the "reports" page. You will then see the new dashboard page. Click "edit" to modify your dashboard (allows adding/removing widgets, dragging-n-droping, resizing).

-----

Planned future changes:
- [x] ability to rename cashflow/networth/spending widgets from the dashboard page - #3284
- [x] ability to add text (markdown) widgets - #3288
- [x] ability to save filters on cashflow/network/spending widgets - and see them in the dashboards page
  - #3364
  - #3417
  - #3432
- [x] ability to rename cashflow/networth/spending widgets from the "inside" page - #3587
- [x] custom reports: refactor how "inner" pages are accessed (w/ unique URL identifiers) - #3744
- [x] bug: cash flow balance is not saved - https://github.com/actualbudget/actual/issues/3671 - #3745
- [x] bug: blank spaces sometimes ([see comment](https://github.com/actualbudget/actual/issues/3282#issuecomment-2407385827)) - #3785

Idea bank:
- [ ] ability to create multiple dashboards & switch between
- [ ] quick layouting tools - i.e. set all widgets to specific size
- [ ] cash flow: ability to switch between the line-graph and condensed widget ([see comment](https://github.com/actualbudget/actual/issues/3282#issuecomment-2393705397) and [this comment](https://github.com/actualbudget/actual/issues/3282#issuecomment-2392682384))
- [ ] custom reports: ability to open a report that is saved, but NOT on a dashboard ([see comment](https://github.com/actualbudget/actual/issues/3282#issuecomment-2392682384))
- [ ] ability to add notes ([see comment](https://github.com/actualbudget/actual/issues/3282#issuecomment-2408315111))
- [ ] widgets: ability to see the legend ([see comment](https://github.com/actualbudget/actual/issues/3282#issuecomment-2393705397) and [this one](https://github.com/actualbudget/actual/issues/3282#issuecomment-2392682384))

---

Feel free to share your ideas, bug reports and feedback below.

**Comment by matt-fidd** [comment]
@MatissJanis I'm seeing a lot of blank report cards (completely empty, not just placeholders) below all of my reports. Do you know how I could remove these please?

![image](https://github.com/user-attachments/assets/8bb2f892-c518-4f9e-9ae3-9c33324ec617)

**Comment by MatissJanis** [comment]
Would you mind exporting the dashboard and uploading here? That will help debugging.

**Comment by matt-fidd** [comment]
> Would you mind exporting the dashboard and uploading here? That will help debugging.

[dashboard.json](https://github.com/user-attachments/files/16854977/dashboard.json)

**Comment by MatissJanis** [comment]
Something.. somehow.. is adding `null` widgets to the dashboard. I haven't been able to reproduce this as of yet, so no solid patch for it yet. But I'll keep looking!

Let me know if anyone is able to reproduce this reliably and provide step-by-step instructions how to repro.

**Comment by shall0pass** [comment]
I noticed if you have the spending report and the dashboard feature on, the spending report won't show.  But if the dashboard feature is turned off, it's there.

One other question.  Is the "reset to default" supposed to delete all of the custom reports?  I sort of expected it would just change the layout to default sized tiles.

**Comment by MatissJanis** [comment]
> One other question. Is the "reset to default" supposed to delete all of the custom reports? I sort of expected it would just change the layout to default sized tiles. Edit: Took me a minute (thought i lost my reports). It wasn't obvious to me that all of the saved reports were still available, they just had to be added to the dashboard.

Perhaps there's some different wording we could use for that button to make it more clear what it does. Any ideas?

As for losing data: remember that you can always "ctrl+z" ;)

**Comment by Jonathan-Fang** [comment]
As much as I agree to separate "create new custom report" and "add new widget" into separate buttons, I thought that the monthly spending report wasn't add-able because I kept clicking the "custom report" button expecting I would find a menu item saying "spending report" because I wasn't planning on re-arranging the dashboard.

I suggest moving the "add new widget" button to the front, and then I only ever edit dashboard when I want to re-arrange the size of the elements.
![image](https://github.com/user-attachments/assets/c88350c2-70f3-4943-b29e-9e62364d00a8)

**Comment by jfdoming** [comment]
> As much as I agree to separate "create new custom report" and "add new widget" into separate buttons, I thought that the monthly spending report wasn't add-able because I kept clicking the "custom report" button expecting I would find a menu item saying "spending report" because I wasn't planning on re-arranging the dashboard.
> 
> I suggest moving the "add new widget" button to the front, and then I only ever edit dashboard when I want to re-arrange the size of the elements. ![image](https://private-user-images.githubusercontent.com/76038959/368472812-c88350c2-70f3-4943-b29e-9e62364d00a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2Njc0NDYsIm5iZiI6MTcyNjY2NzE0NiwicGF0aCI6Ii83NjAzODk1OS8zNjg0NzI4MTItYzg4MzUwYzItNzBmMy00OTQzLWIyOWUtOWU2MjM2NGQwMGE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDEzNDU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4ZWQ3NDk2NTU4NDllZTFhMjQ1ODY5ZGUzYmU1YjJhZjEyNDEyNDVkODVmMzdhMThkMTRjZTJlOWI2NjU5OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.imA-hyICo_ccGQtTl5u5RnQeKKMrtOa22AYHVRha2IE)

I agree. If we go with this approach we could probably remove the dedicated "add custom report" button and combine it with the other one

**Comment by mitteneer** [comment]
I really like this! Would it be possible, when adding a second spending analysis, that the two aren't linked? I currently have one that shows all purchases, and I would like another that filters out certain categories, but when I apply those filters, both are updated with the same filters. Hope this is the right place to drop this comment, sorry if not!

**Comment by nikolajhendel** [comment]
Reports/dashboards have come a long way in such a short time!
Just updated to latest release (v24.10.0) and wanted to give some feedback/suggestions:

1. Enable detailed cash flow view. The 24.10 update enables the ability to save/edit time period, but the dashboard is still a limited to a single income/expenses bar graph and summary total cash flow. It would be nice if the detailed view (per month bar graph and total cash flow line) could be represented on the dashboard.
2. Add a button to get to all reports (or dropdown list?). If a report is not on dashboard, it's really convoluted to get to a report.

**Comment by matt-fidd** [comment]
https://github.com/actualbudget/actual/issues/3559

**Comment by lucav** [comment]
Hi guys, I am new to Actual and really appreciate your work. 
I am about to move away from excel to use Actual. I installed the actual server a few days ago and it works great.

Two needs for me after the v24.10 update:

1) The cash flow chart works good but I want to see the results directly in the dashboard (instead to click to open).
![image](https://github.com/user-attachments/assets/9444a9ae-3422-4191-b5a6-c32b4f23381f)

2) I like to see also the account balances in a pie chart, so would be great to have a legenda directly in the dashboard (instead to click to open) with the value and relative percentage for each accounts.
![image](https://github.com/user-attachments/assets/9e9131c9-daaa-461d-bb02-0ee7564fab1c)

**Comment by Jonathan-Fang** [comment]
I'm reporting that on tablet and Mobile mode, the report widgets are doing weird alignments, for lack of a better description.

If it doesn't seem broken the first time, click somewhere else like budget and then return to reports and it should replicate.

![Screenshot_20241011_060750_Firefox Beta.jpg](https://github.com/user-attachments/assets/a5b77df7-e819-4a40-906c-1350c0fc3c63)

**Comment by Jonathan-Fang** [comment]
Another feedback is that accounts and budget categories and months all have notes, but reports don't have notes. Next to the renaming function, adding a notes markdown thing sounds like a good idea.

**Comment by youngcw** [comment]
@MatissJanis How much more do you want to add to this before releasing as an MVP?  The idea bank items would be nice, but I don't think those are release stoppers.

**Comment by MatissJanis** [comment]
Thanks for the ping @youngcw . Updated the todo list at the top with the things I am planing on addressing (there might be more though if I spot any glaring issues and/or more feedback comes in). Aiming to get this in the v24.12.0 release.

**Comment by Jonathan-Fang** [comment]
Reporting here that the cash flow widget shows march 2024 to Sept 2024 but when I click into it, it shows april 2024 to october 2024 with all time enabled; I would want the settings in the widget to reflect what it shows on the dashboard.
![image](https://github.com/user-attachments/assets/e84bac0e-a520-4004-87d9-6b3c30f0d910)
![image](https://github.com/user-attachments/assets/9c435b2c-171c-4a76-b20c-42fd0dbc1531)

**Comment by Jonathan-Fang** [comment]
Additionally, I suggest making it possible for like the three biggest payment categories to be automatically calculated from a group of categories, is this already possible or being considered?

**Comment by Jonathan-Fang** [comment]
✅ I'm glad to report that when viewing from tablet back to PC, the alignment no longer breaks. Also I think the mobile implementation of having the reports one by one is good.

❌ The only thing now is that viewing the reports on tablet (the PWA for Firefox Beta for Samsung Tab S7) is still odd.

If it helps for responsive design, the dimensions are 1600 x 2560 pixels, 16:10 ratio (~274 ppi density).
![Screenshot_20241021_172939_Firefox Beta](https://github.com/user-attachments/assets/4af5c2dc-2e61-4de7-89d3-2bf725ab6424)

**Comment by psybers** [comment]
Viewing on phone is also odd.  And I can recreate that weird layout by dragging a desktop Chrome window's right edge to make it very narrow.  For me, it is in a weird order (I would expect the top row first, then second row, etc. but it is somewhat random looking).  And it has a giant gaps in the middle with no reports:

<img width="735" alt="image" src="https://github.com/user-attachments/assets/f8b5500c-a95c-4d09-aa9e-c9797dba6304">

**Comment by MatissJanis** [comment]
I've been trying to reproduce the gaps issue for while now, but sadly haven't been able. If anyone has specific pointers - would appreciate it.

**Comment by youngcw** [comment]
So what happened to me just now that maybe caused the missalignment of the dashboard cards.  

I accessed the budget file from a different computer and the dashboard feature was for some reason disabled.  Because the feature was disabled, there were a networth and a cash flow report now at the top  of the page like normal even though my report dashboard doesn't have those at the top.  If I remember my dashboard layout correctly.  I now have a card that used to be my net worth report that is now showing as a deleted report, and there is a bunch of space between things, I think because I use to have a large table report then some regular size reports after the space.

**Comment by MatissJanis** [comment]
Thanks, I think I now have a semi-consistent way to reproduce the issue. Will try to figure it out and patch.

**Comment by Jonathan-Fang** [comment]
Another thought here, in my case, it looks like it breaks on tablet view because the widgets are each a certain size pixel wise, like for example 30px, and the tablet is different dimensions compared to a desktop computer, so when it's constrained from a big computer to a medium sized tablet, the overflow kicks in and you get these gaps in between widgets.

A proposed solution to this would be to make the widgets not hardcoded by pixel, but rather percentages of the available screen size, so that it would shrink length-wise until it's not feasible anymore, and then switch to the mobile 1 stacked on top of another view.

So if the dashboard is edited via desktop, and then viewed on tablet, the dashboard should still pop up with the same arrangement, just sized to the tablet's length, instead of the exact same pixel size as the desktop.
It's vertically scrollable so the width isn't really an issue.

(I don't know how to read the programming part yet, so correct me if my guess is wrong)

**Comment by MatissJanis** [comment]
--- v24.11.0 ---

**Comment by RemiBorgen** [comment]
I wish the layout was saved between different devices, or atleast did not affect eachother.

I have 3 devices, desktop, laptop, and phone. When i set it up the way i want it on my desktop it doesnt look right on the other 2. If i then correct it there then it don't look correct on the desktop.

There also seems to be some sort of ghost widgets that i can't remove.
![Skjermbilde 2024-11-17 095151](https://github.com/user-attachments/assets/0552cb2a-48af-4b81-9e6c-ea43ec1765de)

**Comment by RahulShagri** [comment]
1. Would be nice to be able to sort bar graphs and pie charts. 
2. Would be nice to be able to remove current month from summary cards. If I want to see my cost of living and I include the current partial month, the cost of living is slightly lower than the real value. 
3. Being able to change the font size of the summary card might be helpful too.

**Comment by MatissJanis** [comment]
The feature has been released. Please open up individual bug report or feature request issues for further change requests.
